// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"go_2601_04/internal/application/article"
	"go_2601_04/internal/application/user"
	article2 "go_2601_04/internal/domain/article"
	user2 "go_2601_04/internal/domain/user"
	"go_2601_04/internal/infrastructure/persistence/mysql"
	"go_2601_04/internal/interfaces/http"
)

// Injectors from wire.go:

func InitializeApp(dsn string) (*gin.Engine, error) {
	db := mysql.NewDatabase(dsn)
	userRepository := mysql.NewUserRepository(db)
	service := user.NewUserService(userRepository)
	userHandler := http.NewUserHandler(service)
	articleRepository := mysql.NewArticleRepository(db)
	articleService := article.NewArticleService(articleRepository)
	articleHandler := http.NewArticleHandler(articleService)
	engine := setupRouter(userHandler, articleHandler)
	return engine, nil
}

// wire.go:

// repository
var repositorySet = wire.NewSet(mysql.NewUserRepository, wire.Bind(new(user2.Repository), new(*mysql.UserRepository)), mysql.NewArticleRepository, wire.Bind(new(article2.Repository), new(*mysql.ArticleRepository)))

// service
var serviceSet = wire.NewSet(user.NewUserService, article.NewArticleService)

// handler
var handlerSet = wire.NewSet(http.NewUserHandler, http.NewArticleHandler)

func setupRouter(u *http.UserHandler, a *http.ArticleHandler) *gin.Engine {
	r := gin.Default()
	u.Register(r)
	a.Register(r)
	return r
}
